import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Agregarimg from '@/componentes/imagenes.js'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  function deslizarImagenesAdelante() {
    const carrete = document.querySelector('#carrete');
    carrete.scrollBy({
      left: 400,
      behavior: 'smooth'
    });
  };
  
  function deslizarImagenesAtras() {
    const carrete = document.querySelector('#carrete');
    carrete.scrollBy({
      left: -400,
      behavior: 'smooth'
    });
  };
  
  function desplazarImagenesOnWheel(event) {
    
    function deslizarrapido1() {
      const carrete = document.querySelector('#carrete');
      carrete.scrollBy({
        left: 700,
        behavior: 'smooth'
      });
    };
    
    function deslizarrapido2() {
      const carrete = document.querySelector('#carrete');
      carrete.scrollBy({
        left: -700,
        behavior: 'smooth'
      });
    };

    if (event.deltaY < 0) {
      deslizarrapido1();
    } else if (event.deltaY > 0) {
      deslizarrapido2();
    }
  }


const imgrym = [ {image:"https://rickandmortyapi.com/api/character/avatar/1.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/2.jpeg"}, 
{image:"https://rickandmortyapi.com/api/character/avatar/3.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/4.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/5.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/6.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/7.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/8.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/9.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/10.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/11.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/12.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/13.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/14.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/15.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/16.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/17.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/18.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/19.jpeg"},
{image:"https://rickandmortyapi.com/api/character/avatar/20.jpeg",} ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      
    <div id="div1" className="container mx-auto flex m-3 overflow-hidden">

    <button id="prev" onClick={deslizarImagenesAtras}>&lt;</button>
    
    <div className="m-3 p-3 flex flex-row overflow-hidden snap-mandatory snap-x"
     id="carrete" onWheel={desplazarImagenesOnWheel}>

      {imgrym.map(element =>
      <Agregarimg src={element.image} height="auto" width="100%"></Agregarimg>)}


    </div>

    <button id="next" onClick={deslizarImagenesAdelante}>&gt;</button>

    </div>
      
      </main>
    </>
  )
}
